# Generated by matugen -- sourced by apply-colors for colors it sets at
# runtime (Hyprland's active and inactive borders). Hex without the leading #.
accent={{colors.primary.default.hex_stripped}}
accent2={{colors.tertiary.default.hex_stripped}}
outline={{colors.outline_variant.default.hex_stripped}}
